---
- name: add bash_profile
  copy:
    src: bash_profile
    dest: /Users/max/.bash_profile
    owner: max
    group: staff
    mode: 0644

- name: add bashrc
  copy:
    src: bashrc
    dest: /Users/max/.bashrc
    owner: max
    group: staff
    mode: 0644

- name: make .bashrc.d directory
  file:
    path: /Users/max/.bashrc.d
    state: directory
    owner: max
    group: staff
    mode: 0755

- name: copy bash source files
  copy:
    src: '{{ item }}'
    dest: /Users/max/.bashrc.d/{{ item }}
    owner: max
    group: staff
    mode: 0644
  loop:
    - prompt
    - path
    - editor
