---
- name: install sublime-text
  homebrew_cask:
    name: sublime-text

- name: copy configuration files
  copy:
    src: '{{ item }}'
    dest: ~/Library/Application Support/Sublime Text 3/Packages/User/{{ item }}
    owner: max
    group: staff
    mode: 0644
  loop:
    - Custom.sublime-commands
    - Default (OSX).sublime-keymap
    - Package Control.sublime-settings
    - Plain text.sublime-settings
    - Preferences.sublime-settings
    - Python.sublime-settings
    - Ruby.sublime-settings
    - YAML.sublime-settings
